# Generated by Django 4.0.1 on 2022-02-14 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('about', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=10)),
                ('admission_number', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
            ],
        ),
    ]
