# Generated by Django 4.0.1 on 2022-02-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0007_student_delete_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='std',
            field=models.CharField(max_length=20),
        ),
    ]
