# Generated by Django 4.0.1 on 2022-02-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0009_alter_student_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
