# Generated by Django 4.0.1 on 2022-02-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0011_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn_no',
            new_name='unique_no',
        ),
        migrations.AddField(
            model_name='book',
            name='book_img',
            field=models.ImageField(default=1, upload_to='asset/book_image/'),
            preserve_default=False,
        ),
    ]
