# Generated by Django 4.0.1 on 2022-02-17 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0012_rename_isbn_no_book_unique_no_book_book_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='unique_no',
        ),
    ]
