# Generated by Django 4.0.1 on 2022-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_management', '0013_remove_book_unique_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
